FORMAT: 1A
HOST: https://api.test.paysafe.com/subscriptionsplans/v1/

# Paysafe Subscriptions and Plans 

# Release Notes

| Version   | Date          | Details |
|---        |---            |---      |
| 1.0       | August 2018 | <ul><li>Document release</li></ul>|

# Overview

The Paysafe Subscriptions and Plans API allows merchants 


<a name="apikey" title="Authentication"></a>
# Authentication 

In order for you to use the Paysafe REST API, Paysafe must first set you up on their system
and provide you with an API key. Your API key looks something like this:
 * Key ID – PartnerXYZ
 * Key Password – B-tst1-0-51ed39e4-312d02345d3f123120881dff9bb4020a89e8ac44cdfdcecd702151182fdc952272661d290ab2e5849e31bb03deede7e

The case-sensitive API key is sent using HTTP Basic Authentication. To use HTTP Basic Authentication, you must send the API key credentials using the Authorization header with every request. The Authorization header is constructed as follows:
 1. The Key ID and Key Password are combined into a string separated by a colon, e.g.,“Key ID:Key Password”.
 2. The resulting string literal is then encoded using Base64.
 3. The authorization method and a space (i.e., “Basic”) are then put before the encoded string.

For example, using the Key ID and Password examples above, the header is formed as follows:

`Authorization: Basic
UGFydG5lclhZWjpCLXRzdDEtMC01MWVkMzllNC0zMTJkMDIzNDVkM2YxMjMxMjA4ODFkZmY5YmI0MDIwYTg5ZThhYzQ0Y2RmZGNlY2Q3MDIxNTExODJmZGM5NTIyNzI2NjFkMjkwYWIyZTU4NDllMzFiYjAzZGVlZGU3ZQ==`

For additional details, please refer to [http://en.wikipedia.org/wiki/Basic_access_authentication](http://en.wikipedia.org/wiki/Basic_access_authentication).

**Note:** Your Production API key will be different from your Test API key. Contact your account manager for details. You must keep your API keys safe and ensure that they are used appropriately for your needs.

# URLs 

##  Test URL
In order to test your integration with Paysafe, use the following Test URL:

`https://api.test.paysafe.com`

For example:

`https://api.test.paysafe.com//subscriptionsplans/v1/plans`

## Production URL
In order to process live requests with Paysafe, use the following Production URL:

`https://api.paysafe.com`

For example:

`https://api.paysafe.com//subscriptionsplans/v1/plans`

<a name="pagination" title="Pagination"></a>
# Pagination

In the case where an API GET request returns multiple results, Paysafe returns the first 10 records by default and uses HATEOAS links to provide page navigation. In addition to the default behavior, it is also possible to control the number of results and starting point by passing in query parameters as follows:

## Query Parameters for Pagination


| Name      | Description                                                                           |
|-----------|---------------------------------------------------------------------------------------|
| limit     | This is the total number of records to  return. Default value is 10. Max value is 50. |
| offset    | This is the starting position, where 0 is the first record. Default value is 0.       |
| startDate | This is the start date in UTC. Default value is 30 days before the endDate.           |
| endDate   | This is the end date in UTC. Default value is the current date and time.              |

<a name="globalinvalidcharacters" title="Global Invalid Characters"></a>
# Global Invalid Characters

You must not include any of the characters in the following table as values in any of your request parameters. If you do, your request will result in an error.

|    Character    |    HEX    |    Description                     |
|-----------------|-----------|------------------------------------|
| "               | 22        | Double quotes (or speech marks)    |
| ;               | 3B        | Semicolon                          |
| ^               | 5E        | Caret, circumflex                  |
| *               | 2A        | Asterisk                           |
| <               | 3C        | Less than (or open angled bracket) |
| /               | 2F        | Slash or divide                    |
| [               | 5B        | Opening bracket                    |
| ]               | 5D        | Closing bracket                    |
| \               | 5C        | Backslash                          |


# API 

The Subscriptions and Plans API allows merchants to set up subscription plans for repeat payments using the REST protocol. The protocol uses JSON for all requests and responses.

The following request types are supported:

  * [Plans](#plans)
  * [Subscriptions](#subscriptions)
  
**API Endpoint**

`https://api.paysafe.com/subscriptionsplans/v1/`  

**Resource Patterns**

|Endpoint URL                                           |Description                            |Action |
|---                                                    |---                                    |---    |
|/subscriptionsplans/v1/plans                           |Create a Plan                          |POST   |
|/subscriptionsplans/v1/plans/{plan_id}                 |Look Up a Plan                         |GET    |
|/subscriptionsplans/v1/plans/{plan_id}/subscriptions   |Look Up Subscriptions for a Plan       |GET    |
|/subscriptionsplans/v1/plans/{plan_id}                 |Update a Plan                          |PUT    |
|/subscriptionsplans/v1/plans/{plan_id}                 |Update a Plan                          |PATCH  |
|/subscriptionsplans/v1/plans/{plan_id}                 |Activate a Plan                        |PATCH  |
|/subscriptionsplans/v1/plans/{plan_id}                 |Delete a Plan                          |DELETE |
|/subscriptionsplans/v1/plans/{plan_id}/subscriptions   |Create a Subscription                  |POST   |
|/subscriptionsplans/v1/subscriptions/{subscription_id} |Look Up a Subscription                 |GET    |
|/subscriptionsplans/v1/subscriptions                   |Look Up Subscriptions for a Merchant   |GET    |
|/subscriptionsplans/v1/subscriptions/{subscription_id} |Update a Subscription                  |PUT    |
|/subscriptionsplans/v1/subscriptions/{subscription_id} |Update a Subscription                  |PATCH  |
|/subscriptionsplans/v1/subscriptions/{subscription_id} |Cancel a Subscription                  |PATCH  |
|/subscriptionsplans/v1/subscriptions/{subscription_id} |Delete a Subscription                  |DELETE |



# Getting Started

Click [here](https://developer.paysafe.com/en/rest-api/subscriptions/typical-api-calls/) for details of some common scenarios for creating plans and subscriptions with the Subscriptions and Plans API.

# Testing Instructions

The Paysafe Test environment can be used to test applications without actually running requests through the live system. It is important to make sure that your systems are working correctly before going into a Live environment. Click [here](https://developer.paysafe.com/en/rest-api/subscriptions/test-and-go-live/) for details of using the Test environment.

<a name="isostandards" title="ISO Standards"></a>
# ISO Standards

<a name="currencycodes" title="Currency Codes"></a>
## Currency Codes

**Note:**
 * The table below lists the currencies in which transaction requests are processed, but note that they may be settled in a different currency. 
 * Not all currencies are supported by all banks. Contact your account manager for more information about which currencies are supported for your merchant account.

|Currency |Code |
|--- |--- |
|Argentine Peso |ARS |
|Australian Dollar  |AUD |
|Azerbaijanian Manat    |AZN |
|Bahraini Dinar |BHD  |
|Belarusian Ruble   |BYR  |
|Bolivian Boliviano |BOB  |
|Bosnia and Herzegovina Convertible Mark |BAM  |
|Brazilian Real |BRL  |
|Bulgarian Lev  |BGN  |
|Canadian Dollar    |CAD  |
|Chilean Peso   |CLP  |
|China Yuan Renminbi    |CNY  |
|Columbian Peso |COP  |
|Costa Rican Colon  |CRC  |
|Croatian Kuna  |HRK  |
|Czech Koruna   |CZK  |
|Danish Krone   |DKK  |
|Dominican Peso |DOP  |
|East Caribbean Dollar  |XCD  |
|Egyptian Pound |EGP  |
|Ethiopian Birr |ETB  |
|Euro   |EUR  |
|Fiji Dollar    |FJD  |
|Georgian Lari  |GEL  |
|Guatemala Quetzal  |GTQ  |
|Haiti Goude    |HTG  |
|Honduran Lempira   |HNL  |
|Hong Kong Dollar   |HKD  |
|Hungarian Forint   |HUF  |
|Iceland Krona  |ISK  |
|Indian Rupee   |INR  |
|Indonesia Rupiah   |IDR  |
|Iranian Rial   |IRR  |
|Jamaican Dollar    |JMD  |
|Japanese Yen   |JPY  |
|Jordanian Dinar    |JOD  |
|Kazakhstan Tenge   |KZT  |
|Kenyan Shilling    |KES  |
|Korean Won |KRW  |
|Kuwaiti Dinar  |KWD  |
|Latvian Lats   |LVL  |
|Lebanese Pound |LBP  |
|Libyan Dinars  |LYD  |
|Lithuanian Litas   |LTL  |
|Malawi Kwacha  |MWK  |
|Malaysian Ringgit  |MYR  |
|Mauritius Rupee    |MUR  |
|Mexican Peso   |MXN  |
|Moldovan Leu   |MDL  |
|Moroccan Dirham    |MAD  |
|New Israeli Shekel |ILS  |
|New Zealand Dollar |NZD  |
|Nigerian Naira |NGN  |
|Norwegian Krone    |NOK  |
|Omani Rial |OMR  |
|Pakistan Rupee |PKR  |
|Panamanian Balboa  |PAB  |
|Paraguayan Guarani |PYG  |
|Peruvian Sol   |PEN  |
|Philippine Peso    |PHP  |
|Polish Zloty   |PLN  |
|Pound Sterling |GBP  |
|Qatari Rial    |QAR  |
|Romanian New Leu   |RON  |
|Russian Ruble  |RUB  |
|Saudi Arabian Riyal    |SAR  |
|Serbian Dinar  |RSD  |
|Singapore Dollar   |SGD  |
|South African Rand |ZAR  |
|Sri Lanka Rupee    |LKR  |
|Swedish Krona  |SEK  |
|Swiss Franc    |CHF  |
|Syrian Pound   |SYP  |
|Taiwan New Dollar  |TWD  |
|Thai Baht  |THB  |
|Trinidad and Tobago Dollar |TTD  |
|Tunisian Dinar |TND  |
|Turkish Lira   |TRY  |
|Ukranian Hryunia   |UAH  |
|UAE Dirham |AED  |
|Uruguay Peso   |UYU  |
|US Dollar  |USD  |
|Venezuelan Bolivar |VEF  |
|Viet Nam Dong  |VND  |


# Complex JSON Objects

<a name="billingcycleobject" title="billingCycle Object"></a>
## billingCycle

|Element                        |Type                       |Description                        |
|---                            |---                        |---       |
|frequency                      |enum                       |Combine this value with the *interval* element to specify how often a subscription should be billed. <ul><li>DAILY</li><li>MONTHLY</li><li>YEARLY</li></ul>|
|interval                       |number<br/>`max=999`       |Combine this value with the *frequency* element to specify the number of time units between each subscription payment. For example, to create a monthly plan, set *frequency* to MONTHLY and *interval* to 1. To create a weekly plan, *frequency* to DAILY and *interval* to 7. </br>**Note:** Semi-weekly (twice a week) and semi-monthly (twice a month) plans are not currently supported. |

```apib
    {
    "billingCycle": {
        "frequency": "DAILY",
        "interval": "7"
    }
    }
```

<a name="dateofbirthobject" title="dateOfBirth Object"></a>
## dateOfBirth
|Element            |Type                           |Required       |Description    |
|---                |---                            |---            |---            |
|year               |number<br/>`length=4 min=1900` |Yes            |This is the year of the customer’s birth.|
|month              |number<br/>`length=2 max=12`   |Yes            |This is the month of the customer’s birth.|
|day                |number<br/>`length=2 max=31`   |Yes            |This is the day of the customer's birth.|

```apib
            { 
               "dateOfBirth": {
                  "year": 1980,
                  "month": 12,
                  "day": 25
                }
            }
```

<a name="errorobject" title="error Object"></a>
## error
|Element            |Type       |Description                        |
|---                |---        |---                                |
|code               |string     |The error code. Also shown in the X-Application-Status-Code response header.            |
|message            |string     |A description of the error.                 |
|details            |string array     |Details of any parameter value errors (optional).       |
|links              |link array     |One or more rel/href pairs, where rel is "errorinfo", and href is the Developer Center URL containing a description of the error.|

```apib
   {
   "error":{  
      "code":"5270",
      "message":"The credentials provided with the request do not have permission to access the data requested.",
      "details":[  
         "access to {Account:1001076700} denied"
      ],
      "links":[  
         {  
            "rel":"errorinfo",
            "href":"https://developer.paysafe.com/en/rest-api/subscriptionsplans/test-and-go-live/subscription-errors/#ErrorCodeXXXX"
         }
      ]
   }
   }
```

<a name="nextpaymentobject" title="nextPayment Object"></a>
## nextPayment

|Element                        |Type                       |Description                        |
|---                            |---                        |---       |
|amount                         |number                     |This is the amount of the payment, in minor units. |
|accountId                      |string<br/>`length<=36`    |This is the merchant account that is used to process the payment.|
|paymentToken                   |string<br/>`length<=50`    |This is the payment token used for the payment. |
|paymentMethod                  |enum                       |This is the payment method used for the payment. <ul><li>CC &ndash; credit card</li><li>DD_ACH &ndash; ACH bank account</li><li>DD_EFT &ndash; EFT bank account</li><li>DD_BACS &ndash; BACS bank account</li><li>DD_SEPA &ndash; SEPA bank account</li></ul>|
|paymentDate                    |YYYY-MM-DD                 |This is the next scheduled payment date. |

```apib
{
  "amount": "4999",
  "accountId": "1000055555",
  "paymentToken": "CNjEzMTM4NDg1",
  "paymentMethod": "CC",
  "paymentDate": "2017-11-01"
}
```

<a name="planobject" title="plan Object"></a>
## Plan

|Element                        |Type                       |Description                        |
|---                            |---                        |---       |
|id                             |string<br/>`length<=36`    |This is the unique plan ID returned in the response.|
|name                           |string<br/>`length=4-50`   |This is the plan name. |
|version                        |number<br/>`max=4`         |The plan version, returned in the response. |
|description                    |string<br/>`length<=255`   |This is a description of the plan. |
|amount                         |number<br/>`max=99999999999`   |This is the amount of the payment, in minor units. |
|currencyCode                   |string<br/>`length=3`      |This is the currency used for the plan amounts, e.g., USD or CAD. See [Currency Codes](#currencycodes)|
|billingCycle                   |[billingCycle](#billingcycleobject)    |These are details of the billing cycle.    |
|startDate                      |string<br/>`YYYY-MM-DD`    |This is the date the plan starts. **Note:** This defaults to the current date. |
|endDate                        |string<br/>`YYYY-MM-DD`    |This is the date the plan ends. **Note:** If no end date is specified, the plan is valid indefinitely. Once the end date for the plan is reached, no new subscriptions can be created for that plan. However, any existing subscriptions associated with this plan will continue. |
|status                         |enum                       |This is the status of the plan.<ul><li>INITIAL &ndash; The plan has been newly created. A plan with this status cannot be used to create a subscription. All parameters can be changed when a plan is in this status.</li><li>ACTIVE &ndash; The plan can be used to create subscriptions. Once a plan is active, only specific parameters can be changed.</li><li>INACTIVE &ndash; The plan can not be used to create a subscription. Existing subscriptions for this plan will continue to be billed until they expire or are cancelled. The plan can no longer be updated.</li><li>EXPIRED &ndash; The the plan *endDate* is now in the past. The plan can no longer be used to create a subscription. Existing subscriptions for this plan will continue to be billed until they expire or are cancelled, but the plan can no longer be updated.</li></ul>|
|error                          |[error](#errorobject)      |These are details if an error occurs. |
|creationTime                   |UTC formatted date         |This is the date and time the plan was created.|
|lastUpdatedTime                |UTC formatted date         |This is the date and time the plan was last updated. |


```apib
{
  "name": "Gold",
  "description": "The Gold plan",
  "amount": 5000,
  "currencyCode": "USD",
  "billingCycle": {
    "frequency": "DAILY",
    "interval": 7
  },
  "startDate": "2017-09-01",
  "endDate": "2018-08-31"
}  
```

<a name="profileobject" title="profile Object"></a>
## Profile

|Element            |Type                               |Required   |Description    |
|---                |---                                |---        |---            |
|id                 |string <br/>`length<=36`           |           |This is the ID returned in the response.|
|status             |enum                               |           |This is the status of the customer profile. Possible values are:<br/><ul><li>INITIAL</li><li>ACTIVE</li></ul><br/>By default the system automatically sets the profile status to an ACTIVE state. If you want to prevent the profile from being used for payments, you can set the status to an INITIAL state (e.g., in cases where you first want to validate the customer).|
|merchantCustomerId |string <br/>`length<=100`          |Yes        |This is a customer ID that the merchant provides with the request for their own internal customer identification. This value must be unique for each customer belonging to a merchant.|
|locale             |enum                               |Yes        |This indicates the language of the profile. Possible values are:<ul><li>en_US</li><li>fr_CA</li><li>en_GB</li></ul>
|firstName          |string <br/>`length<=80`           |           |This is the customer’s first name. |
|middleName         |string <br/>`length<=80`           |           |This is the customer’s middle name. |
|lastName           |string <br/>`length<=80`           |           |This is the customer’s last name. |
|dateOfBirth        |[dateOfBirth](#dateofbirthobject)  |           |This is the customer's date of birth.|
|ip                 |string<br/>`length<=46`            |           |This is the customer’s IP address.|
|gender             |enum                               |           |This is the customer’s gender. Possible values are:<ul><li>M (male)</li><li>F (female)</li></ul>
|nationality        |string<br/>`length<=30`            |           |This is the customer’s nationality.|
|email              |string<br/>`length<=255`           |           |This is the customer's email address.|
|phone              |string<br/>`length<=40`            |           |This is the customer's phone number.|
|cellPhone          |string<br/>`length<=40`            |           |This is the customer's cell phone number.|
|paymentToken       |string><br/>`length<=50`           |           |This is a token generated by Paysafe that represents the customer and returned in the response to the profile request.|


```apib
    {
        "id": "a5f1889d-f1be-4bbf-941d-fd9b8d09d5b1",
        "status": "ACTIVE",
        "merchantCustomerId": "john.smith1400783052032",
        "locale": "en_US",
        "firstName": "John",
        "middleName": "James",
        "lastName": "Smith",
        "dateOfBirth": {
            "year": 1990,
            "month": 12,
            "day": 29
        },
        "gender": "M",
        "paymentToken": "CNjEzMTM4NDg1"
    }
```

<a name="previouspaymentobject" title="previousPayment Object"></a>
## previousPayment

|Element                        |Type                       |Description                        |
|---                            |---                        |---       |
|amount                         |number                     |This is the amount of the payment, in minor units. |
|accountId                      |string<br/>`length<=36`    |This is the merchant account that is used to process the payment.|
|paymentToken                   |string<br/>`length<=50`    |This is the payment token used for the payment. |
|paymentMethod                  |enum                       |This is the payment method used for the payment. <ul><li>CC &ndash; credit card</li><li>DD_ACH &ndash; ACH bank account</li><li>DD_EFT &ndash; EFT bank account</li><li>DD_BACS &ndash; BACS bank account</li><li>DD_SEPA &ndash; SEPA bank account</li></ul>|
|paymentDate                    |YYYY-MM-DD                 |This is the payment date. |
|status                         |enum                       |This is the status of the payment request.<ul><li>PENDING &ndash; The payment has not been completed yet.</li><li>COMPLETED &ndash; The payment was successful.</li><li>HELD &ndash; The payment request was made but was not sent to the gateway due to a risk rule.</li><li>CANCELLED &ndash; The payment was cancelled.</li><li>FAILED &ndash; The payment request received an error or was declined.</li></ul> |
|error                          |[error](#errorobject)      |These are details if an error occurs with the payment. |

```apib
{
  "amount": "4999",
  "accountId": "1000055555",
  "paymentToken": "CNjEzMTM4NDg1",
  "paymentMethod": "CC",
  "paymentDate": "2017-10-01",
  "status": "PENDING"
}
```

<a name="retrypaymentobject" title="retryPayment Object"></a>
## retryPayment

|Element                        |Type                       |Description                        |
|---                            |---                        |---       |
|amount                         |number                     |This is the amount of the payment, in minor units. |
|accountId                      |string<br/>`length<=36`    |This is the merchant account that is used to process the payment.|
|paymentToken                   |string<br/>`length<=50`    |This is the payment token used for the payment. |
|paymentMethod                  |enum                       |This is the payment method used for the payment. <ul><li>CC &ndash; credit card</li><li>DD_ACH &ndash; ACH bank account</li><li>DD_EFT &ndash; EFT bank account</li><li>DD_BACS &ndash; BACS bank account</li><li>DD_SEPA &ndash; SEPA bank account</li></ul>|
|paymentDate                    |YYYY-MM-DD                 |This is the date to retry the payment.|

```apib
{
  "amount": "4999",
  "accountId": "1000055555",
  "paymentToken": "CNjEzMTM4NDg1",
  "paymentMethod": "CC",
  "paymentDate": "2017-09-01"
}  
```

<a name="scheduleobject" title="schedule Object"></a>
## Schedule

|Element                        |Type                       |Description                        |
|---                            |---                        |---       |
|previousPayment                |[previousPayment](#previouspaymentobject)  |These are details of the previous regularly scheduled payment.|
|retryPayment                   |[retryPayment](#retrypaymentobject)        |These are details of the payment to be retried on a previous payment failure. |
|nextPayment                    |[nextPayment](#nextpaymentobject)          |These are the details of the next regularly scheduled payment. |

```apib
{
"previousPayment": {
  "amount": "4999",
  "accountId": "1000055555",
  "paymentToken": "CNjEzMTM4NDg1",
  "paymentMethod": "CC",
  "paymentDate": "2017-10-01",
  "status": "PENDING"
  },
"nextpayment": {
  "amount": "4999",
  "accountId": "1000055555",
  "paymentToken": "CNjEzMTM4NDg1",
  "paymentMethod": "CC",
  "paymentDate": "2017-11-01"
  }
}
```

<a name="subscriptionobject" title="subscription Object"></a>
## Subscription

|Element                        |Type                       |Description                        |
|---                            |---                        |---       |
|id                             |string<br/>`length<=36`    |This is the unique subscription ID returned in the response.|
|accountId                      |string<br/>`length<=36`    |This is the merchant account that is used to process this subscription. **Note:** The processing currency of the merchant account must be the same as the plan's currency, except if it is a load balancing master account. |
|paymentToken                   |string<br/>`length<=50`    |This is the [card payment token](http://paysafegroup.github.io/paysafe_api_customervault_v1/#/reference/0/cards/create-a-card) or the [bank account payment token](http://paysafegroup.github.io/paysafe_api_customervault_v1/#/reference/0/eft-bank-accounts/create-an-eft-bank-account) to be used for billing the customer. |
|paymentDescriptor              |string<br/>`length<=12`    |This is a descriptor that will appear on the consumer's credit card or bank account statement. It will be passed to the card payment's *merchantDescriptor.dynamicDescriptor* element or to the bank payment's  *paymentDescriptor* element.|
|itemQuantity                   |number<br/>`min=1`         |This is the number of items in the subscription.|
|startDate                      |string<br/>`YYYY-MM-DD`    |This is the date the subscription starts. **Note:**  If not provided, the start date of the plan is used unless it is in the past, in which case the current date is used.|
|endDate                        |string<br/>`YYYY-MM-DD`    |This is the date the subscription ends. **Note:** If not provided, the subscription will continue indefinitely. |
|billingPeriodStartDate         |string<br/>`YYYY-MM-DD`    |This is the date the billing period starts, returned in the response. |
|billingPeriodEndDate           |string<br/>`YYYY-MM-DD`    |This is the date the billing period ends, returned in the request response.|
|plan                           |[plan](#planobject)        |This is the full plan information, returned in the request response. |
|profile                        |[profile](#profileobject)  |This is the customer's full [profile information from the Paysafe Customer Vault](http://paysafegroup.github.io/paysafe_api_customervault_v1/#/reference/0/profiles/create-a-profile), returned in the request response. |
|merchantRefNum                 |string<br/>`length<=255`   |This is the merchant reference number, an identifier created by the merchant and submitted as part of the request.|
|dupCheck                       |boolean                    |This validates that this request is not a duplicate. A request is considered a duplicate if the *merchantRefNum* has already been used in a previous request within the past 90 days.<br/>**Note:** This value defaults to *true*.|
|reAttemptPayment               |boolean                    |In the case of a payment failure, this automatically retries the payment one time. <br/>**Note:** This value defaults to *true*. <br>Currently, this is supported for credit card payments only. For Direct Debit payments, the standard representment process will apply, if configured for your merchant account and supported by your bank scheme. For more information, contact your account manager.|
|reasonForSuspension            |string<br/>`length<=255`   |This is the reason for suspending the subscription. If it is suspended automatically by Paysafe due to payment failure, this value will be set to "Subscription suspended due to failed payment". |
|status                         |enum                       |This is the status of the subscription. **Note:** Defaults to ACTIVE. A subscription with the status of CANCELLED or EXPIRED cannot be modified. <ul><li>ACTIVE &ndash; The subscription is generating regular billings.</li><li>CANCELLED &ndash; The subscription has been cancelled, so no billings are  generated.</li><li>EXPIRED &ndash; The subscription has reached the end date.</li><li>PAST_DUE &ndash; One or more payment attempts have failed and re-attempt(s) have been scheduled; scheduled billings are still being generated.</li><li>SUSPENDED &ndash; The subscription is temporarily not generating billings.</li></ul> |
|effectiveCancellationDate      |string<br/>`YYYY-MM-DD`    |This is the date the subscription cancellation takes effect, returned in the response. This will be in the future if the payment for the current billing cycle has already been created. |
|reasonForCancellation          |string<br/>`length<=255`   |This is the reason for cancelling the subscription.|
|schedule                       |[schedule](#scheduleobject)    |These are schedule details. |
|error                          |[error](#errorobject)      |These are details if an error occurs. |
|creationTime                   |UTC formatted date         |This is the date and time the subscription was created.|
|lastUpdatedTime                |UTC formatted date         |This is the date and time the subscription was last updated. |

```apib
    {
      "accountId": "1000055555",
      "paymentToken": "CNjEzMTM4NDg1",
      "paymentDescriptor": "800-555-1212",
      "merchantRefNum": "Sub19C24",
      "dupCheck": true,
      "itemQuantity": 2,
      "status": "ACTIVE",
      "startDate": "2015-10-10",
      "endDate": "2016-12-31"
    }  
```



# Error Summary

Click [here](https://developer.paysafe.com/en/rest-api/partners/account-management/test-and-go-live/account-management-errors/) for a summary and description of errors you might encounter using the Account Management API.

# Using the Console Window
To configure and test the example in the Console window, click **Switch to Console**. 
In the Console window, you can update the headers, the request body, and parts of the API endpoint. 
For example, for most requests you must update the endpoint to include your profile ID (returned when you create a profile), which you do by selecting **URI Parameters** and then updating the **profile_id** value. 
You must also update the Header to include your API Key, which you do by selecting **Headers** and then updating the **Authorization** value. 
To get your API key User name and Password, log into the Paysafe Back Office and choose **Settings > API Key**. 
To then generate the API Key, concatenate your User name and Password, separated by a colon, then Base64 encode it, and then prefix it with "Basic ".
When you are ready to test your example, you can switch between the Production and Mock server environment:
* Production server – This calls the resource on Paysafe's Test system. 
* Mock server – This environment simply returns the dummy values in the example response irrespective of the parameters you supply. You do not need to use your profile ID or Test API key for this request.

To call the API resource, click **Call Resource**. The response is displayed in the Console window.

# Legal and Community
<ul>
<li><a href="https://www.paysafe.com/privacy-policy/" target="_blank">Privacy Policy</a></li>
<li><a href="https://developer.paysafe.com/en/resources-and-support/terms-of-use/" target="_blank">Terms of Use</a></li>
<li><a href="http://www.paysafe.com/regulatory-disclosure/" target="_blank">Regulatory Disclosures</a></li>
<li><a href="http://community.paysafe.com/spaces/11/index.html" target="_blank">FAQs</a></li>
<li><a href="http://community.paysafe.com/index.html" target="_blank">Community</a></li>
<li><a href="http://community.paysafe.com/spaces/10/index.html" target="_blank">Paysafe Blog</a></li>
</ul>

## Verify That the Service Is Accessible [GET /monitor]
<a name="verifyservice" title="Verify Service"></a>

This call returns a status of READY if the API is available.

+ Response 200 (application/json)

  + Body

            {
                "status" : "READY"
            }

# Plans [/plans]
<a name="plans" title="Plans"></a>

## Create a Plan [POST /plans]
<a name="createplan" title="Create a Plan"></a>

This is how you submit a plan creation request.

+ Request Plan Creation (application/json)

    + Attributes
        + Include Plan
        
    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY

+ Response 200 (application/json)

    + Attributes
        + Include Plan Response

## Look Up a Plan [GET /plans/{plan_id}]
<a name="getplan" title="Look Up a Plan"></a>

This is how you look up a plan using the ID returned in the response to the original request.

+ Parameters

    + plan_id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the unique plan ID, returned in the response to the plan creation request.

+ Request Get Plan (application/json)
    
    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY
            
+ Response 200 (application/json)

    + Attributes    
        + Include Plan Response

## Look Up All Plans Belonging to a Merchant [GET /plans]
<a name="getplansmerchant" title="Look Up All Plans Belonging to a Merchant"></a>

This is how you look up a all plans belonging to a single merchant.

+ Request Get Plan (application/json)
    
    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY
            
+ Response 200 (application/json)

    + Attributes    
        + Include Plan Response All Plans

## Update a Plan - PUT [PUT /plans/{plan_id}]
<a name="updateplan" title="Update a Plan - PUT"></a>

This is how you update a plan with a PUT request. For example, you can change the plan status from *INITIAL* to *ACTIVE*.

**Note:** All parameters can be updated when a plan is in the *INITIAL* status. Elements that are part of an existing plan that are not included in the update request will be set to null or to the default value if it has one.

+ Parameters

    + plan_id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the plan ID returned in the response to the plan creation request.
    
+ Request Plan Update (application/json)    

    + Attributes
        + Include Plan Update

    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY  

+ Response 200 (application/json)

    + Attributes
        + Include Plan Update Response

## Update an Active Plan - PUT [PUT /plans/{plan_id}]
<a name="updateplanactive" title="Update an Active Plan"></a>

This is how you update an active plan with a PUT request.

**Note:** Only a subset of parameters can be updated once a plan is in *ACTIVE* status. Elements that are part of an existing plan that are not included in the update request will be set to null or to the default value if it has one.

+ Parameters

    + plan_id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the plan ID returned in the response to the plan creation request.
    
+ Request Plan Update (application/json)    

    + Attributes
        + Include Plan Update Active

    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY  

+ Response 200 (application/json)

    + Attributes
        + Include Plan Update Response

## Update a Plan - PATCH [PATCH /plans/{plan_id}]
<a name="updateplanpatch" title="Update a Plan - PATCH"></a>

This is how you update a plan with a PATCH request. For example, you can change the plan status from *INITIAL* to *ACTIVE*.

**Note:** All parameters can be updated when a plan is in the *INITIAL* status. 

+ Parameters

    + plan_id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the plan ID returned in the response to the plan creation request.
    
+ Request Plan Update (application/json)    

    + Attributes
        + Include Plan Update PATCH

    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY  

+ Response 200 (application/json)

    + Attributes
        + Include Plan Update Response

## Delete a Plan [DELETE /plans/{plan_id}]
<a name="deleteplan" title="Delete a Plan"></a>

This is how you delete a plan.

**Note:** You can delete a plan only if it does not have any subscriptions assigned to it, regardless of the status. Therefore, the primary usage of the DELETE operation is for a merchant who made an error during plan creation and does not want to keep it.

+ Parameters
    + plan_id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the plan ID returned in the response to the plan creation request.

+ Request Delete a Profile (application/json)

    + Headers        

            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY
            
+ Response 200 (application/json)

# Subscriptions [/subscriptions]
<a name="subscriptions" title="Subscriptions"></a>

## Create a Subscription [POST /plans/{plan_id}/subscriptions]
<a name="createsubscription" title="Create a Subscription"></a>

This is how you submit a subscription creation request.

+ Parameters

    + plan_id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the plan ID returned in the response to the plan creation request.

+ Request Subscription Creation (application/json)

    + Attributes
        + Include Subscription
        
    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY

+ Response 200 (application/json)

    + Attributes
        + Include Subscription Response


## Look Up a Subscription [GET /subscriptions/{subscription_id}]
<a name="getsubscription" title="Look Up a Subscription"></a>

This is how you look up a plan using the ID returned in the response to the original request.

+ Parameters

    + subscription_id:`382d5b82-5e3f-40b7-a36d-eb982116c2b3` (string, required) - This is the unique subscription ID, returned in the response to the subscription creation request.

+ Request Get Subscription (application/json)
    
    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY
            
+ Response 200 (application/json)

    + Attributes    
        + Include Subscription Response

## Look Up a Subscription with Resource Expansion [GET /subscriptions/{subscription_id}?expand={expand_elements}]
<a name="getsubscriptionresources" title="Look Up a Subscription with Resource Expansion"></a>

This is how you look up a plan with resource expansion.

+ Parameters

    + subscription_id:`382d5b82-5e3f-40b7-a36d-eb982116c2b3` (string, required) - This is the unique subscription ID, returned in the response to the subscription creation request.
    + expand_elements:`plan,profile`

+ Request Get Subscription with Resource Expansion (application/json)
    
    + Headers
    
            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY
            
+ Response 200 (application/json)

    + Attributes    
        + Include Subscription Response Expansion

# Data Structures

## Billing Cycle
+ frequency:`MONTHLY` (string, required) - This is the billing frequency for the plan.
    - DAILY
    - MONTHLY
    - YEARLY
+ interval:`1` (string, required) - This is the number of time units between each subscription payment. For example, to create a weekly plan, set *frequency* to DAILY and *interval* to 7.

## Date of Birth
+ year:`1980`
+ month:`12`
+ day:`25`

## Plan
+ name:`Gold` (string, required) - This is merchant's name for the plan.
+ description:`Gold plan for Elite members` (string, optional) - This is a short description of the plan.
+ amount:`5000` (string, required) - This is the amount of the plan, in minor units. 
+ currencyCode:`USD` (string, required) - This is [the currency used](#currencyobject) for the plan amounts, e.g., USD or CAD.
+ billingCycle (object, required) - This is the billing cycle of the plan.
    + Include Billing Cycle
+ startDate:`2017-01-01` (string, optional) - This is the date the plan starts.
+ endDate:`2017-12-31` (string, optional) - This is the date the plan ends.
+ status:`ACTIVE` (string, optional) - This is the [status of the plan](#planobject).

## Plan 2
+ name:`Silver` (string, required) - This is merchant's name for the plan.
+ description:`Silver plan for senior members` (string, optional) - This is a short description of the plan.
+ amount:`4000` (string, required) - This is the amount of the plan, in minor units. 
+ currencyCode:`USD` (string, required) - This is [the currency used](#currencyobject) for the plan amounts, e.g., USD or CAD.
+ billingCycle (object, required) - This is the billing cycle of the plan.
    + Include Billing Cycle
+ startDate:`2017-01-15` (string, optional) - This is the date the plan starts.
+ endDate:`2017-12-15` (string, optional) - This is the date the plan ends.
+ status:`ACTIVE` (string, optional) - This is the [status of the plan](#planobject).
    - INITIAL
    - INACTIVE
    - ACTIVE
    - EXPIRED

## Plan Response
+ id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the unique plan ID.
+ version:`1` (number, required) - This is the version of the plan.
+ Include Plan
+ creationTime:`2017-02-14T15:12:18Z` (string, required) - This is the date and time the plan was created.
+ lastUpdatedTime:`2014-04-14T15:12:18Z` (string, required) This is the date and time the plan was last updated.
+ links (array, required) - This is an array of [links](#linksobject).
    + (object)
        + rel:`self` (string, required) - This is the link type that allows different endpoints to be targeted depending on the end state of the transaction.
        + href:`https://api.test.paysafe.com/subscriptionsplans/v1/plans/e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the URI of the resource.

## Plan Response Expansion
+ id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the unique plan ID.
+ version:`1` (number, required) - This is the version of the plan.
+ Include Plan
+ creationTime:`2017-02-14T15:12:18Z` (string, required) - This is the date and time the plan was created.
+ lastUpdatedTime:`2014-04-14T15:12:18Z` (string, required) This is the date and time the plan was last updated.

## Plan Response All Plans
+ plans (array, required) - This is an array of plans.
    + (object)
        + id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the unique plan ID.
        + version:`1` (number, required) - This is the version of the plan.
        + Include Plan
        + creationTime:`2017-02-14T15:12:18Z` (string, required) - This is the date and time the plan was created.
        + lastUpdatedTime:`2014-04-14T15:12:18Z` (string, required) This is the date and time the plan was last updated.
        + links (array, required) - This is an array of [links](#linksobject).
            + (object)
                + rel:`self` (string, required) - This is the link type that allows different endpoints to be targeted depending on the end state of the transaction.
                + href:`https://api.test.paysafe.com/subscriptionsplans/v1/plans/e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the URI of the resource.
    + (object)
        + id:`e067d83f-add7-4b6b-8884-dfa8693ee14r` (string, required) - This is the unique plan ID.
        + version:`1` (number, required) - This is the version of the plan.
        + Include Plan 2
        + creationTime:`2017-02-14T15:12:18Z` (string, required) - This is the date and time the plan was created.
        + lastUpdatedTime:`2014-04-14T15:12:18Z` (string, required) This is the date and time the plan was last updated.
        + links (array, required) - This is an array of [links](#linksobject).
            + (object)
                + rel:`self` (string, required) - This is the link type that allows different endpoints to be targeted depending on the end state of the transaction.
                + href:`https://api.test.paysafe.com/subscriptionsplans/v1/plans/e067d83f-add7-4b6b-8884-dfa8693ee14r` (string, required) - This is the URI of the resource.

## Plan Update
+ name:`Gold` (string, required) - This is merchant's name for the plan.
+ description:`Gold plan for Elite members` (string, optional) - This is a short description of the plan. **Note:** You cannot modify this field in the update request.
+ amount:`5500` (string, required) - This is the amount of the plan, in minor units. **Note:** You cannot modify this field in the update request.
+ currencyCode:`USD` (string, required) - This is [the currency used](#currencyobject) for the plan amounts, e.g., USD or CAD. **Note:** You cannot modify this field in the update request.
+ billingCycle (object, required) - This is the billing cycle of the plan. **Note:** You cannot modify this field in the update request.
    + Include Billing Cycle
+ startDate:`2017-01-01` (string, optional) - This is the date the plan starts. **Note:** You cannot modify this field in the update request.
+ endDate:`2017-12-31` (string, optional) - This is the date the plan ends.
+ status:`ACTIVE` (string, optional) - This is the [status of the plan](#planobject).
    - INITIAL
    - INACTIVE
    - ACTIVE
    - EXPIRED

## Plan Update Response
+ id:`e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the unique plan ID.
+ version:`1` (number, required) - This is the version of the plan.
+ Include Plan Update
+ creationTime:`2017-02-14T15:12:18Z` (string, required) - This is the date and time the plan was created.
+ lastUpdatedTime:`2014-04-14T15:12:18Z` (string, required) This is the date and time the plan was last updated.
+ links (array, required) - This is an array of [links](#linksobject).
    + (object)
        + rel:`self` (string, required) - This is the link type that allows different endpoints to be targeted depending on the end state of the transaction.
        + href:`https://api.test.paysafe.com/subscriptionsplans/v1/plans/e067d83f-add7-4b6b-8884-dfa8693dde1f` (string, required) - This is the URI of the resource.

## Plan Update Active
+ name:`Gold` (string, required) - This is merchant's name for the plan.
+ description:`Gold plan for Elite members` (string, optional) - This is a short description of the plan.
+ amount:`5500` (string, required) - This is the amount of the plan, in minor units. **Note:** You cannot modify this field once the plan is in *ACTIVE* status.
+ currencyCode:`USD` (string, required) - This is [the currency used](#currencyobject) for the plan amounts, e.g., USD or CAD. **Note:** You cannot modify this field once the plan is in *ACTIVE* status.
+ billingCycle (object, required) - This is the billing cycle of the plan. **Note:** You cannot modify these fields once the plan is in *ACTIVE* status.
    + Include Billing Cycle
+ startDate:`2017-01-01` (string, optional) - This is the date the plan starts.
+ endDate:`2017-12-31` (string, optional) - This is the date the plan ends.
+ status:`ACTIVE` (string, optional) - This is the [status of the plan](#planobject).
    - INITIAL
    - INACTIVE
    - ACTIVE
    - EXPIRED

## Plan Update PATCH
+ name:`Gold` (string, optional) - This is merchant's name for the plan.
+ description:`Gold plan for Elite members` (string, optional) - This is a short description of the plan.
+ amount:`5500` (string, optional) - This is the amount of the plan, in minor units. **Note:** You cannot modify this field in the update request.
+ currencyCode:`USD` (string, optional) - This is [the currency used](#currencyobject) for the plan amounts, e.g., USD or CAD. **Note:** You cannot modify this field in the update request.
+ billingCycle (object, optional) - This is the billing cycle of the plan. **Note:** You cannot modify this field in the update request.
    + Include Billing Cycle
+ startDate:`2017-01-01` (string, optional) - This is the date the plan starts.
+ endDate:`2017-12-31` (string, optional) - This is the date the plan ends.
+ status:`ACTIVE` (string, optional) - This is the [status of the plan](#planobject).
    - INITIAL
    - INACTIVE
    - ACTIVE
    - EXPIRED

## Profile
+ id:`a5f1889d-f1be-4bbf-941d-fd9b8d09d5b1` (string, required) - This is the ID returned in the profile creation response.
+ status:`ACTIVE` (enum, required) - This is the status of the customer profile.
    - INITIAL
    - ACTIVE
+ merchantCustomerId:`john.smith1400783052032` (string, required) - This is a customer ID that the merchant provides with the request for their own internal customer identification.
+ locale:`en_US` (string, required) - This indicates the language of the profile.
    - en_US
    - fr_CA
    - en_GB
+ firstName:`John` (string, optional) - This is the customer’s first name.
+ middleName:`James` (string, optional) - This is the customer's middle name.
+ lastName:`Smith` (string, optional) - This is the customer’s last name.
+ dateOfBirth (object, optional) - This is the customer's date of birth.
    + Include Date of Birth
+ ip:`192.0.126.111` (string, optional) - This is the customer’s IP address.
+ gender:`M` (enum, optional) - This is the customer’s gender.
    - M
    - F
+ paymentToken:`CNjEzMTM4NDg1` (string, optional) - This is a token generated by Paysafe that represents the customer and returned in the response to the profile creation request.

## Subscription
+ accountId:`1000055555` (string, required) - This is the merchant account that is used to process this subscription.
+ paymentToken:`CNjEzMTM4NDg1` (string, required) - This is the [card payment token](http://paysafegroup.github.io/paysafe_api_customervault_v1/#/reference/0/cards/create-a-card) or the [bank account payment token](http://paysafegroup.github.io/paysafe_api_customervault_v1/#/reference/0/eft-bank-accounts/create-an-eft-bank-account) to be used for billing the customer.
+ merchantRefNum:`Sub19C24` (string, required) - This is the merchant reference number, an identifier created by the merchant and submitted as part of the request.
+ paymentDescriptor:`800-555-2222` (string, optional) - This is a descriptor that will appear on the consumer's credit card or bank account statement. It will be passed to the card payment's *merchantDescriptor.dynamicDescriptor* element or to the bank payment's *paymentDescriptor* element.
+ dupCheck:`true` (boolean, optional) - This validates that this request is not a duplicate. A request is considered a duplicate if the *merchantRefNum* has already been used in a previous request within the past 90 days. **Note:** This value defaults to *true*.
+ itemQuantity:`2` (string, optional) - The number of items in the subscription.
+ status:`ACTIVE` (string, optional) - This is the [status of the subscription](#subscriptionobject).
+ startDate:`2017-01-01` (string, optional) - This is the date the subscription starts.
+ endDate:`2017-12-31` (string, optional) - This is the date the subscription ends.

## Subscription Response
+ id:`382d5b82-5e3f-40b7-a36d-eb982116c2b3` (string, required) - This is the unique subscription ID.
+ Include Subscription
+ creationTime:`2017-02-14T15:12:18Z` (string, required) - This is the date and time the subscription was created.
+ billingPeriodStartDate:`2017-01-01` (string, optional) - This is the date the billing period starts.
+ billingPeriodEndDate:`2017-12-31` (string, optional) - This is the date the billing period ends.
+ schedule (object, optional)  
    + previousPayment (object, optional) - These are [details about the previous payment](#previouspaymentobject).
        + amount:`4999` - This is the amount of the payment, in minor units.
        + accountId:`1000055555` - This is the merchant account that is used to process the payment.
        + paymentToken:`CNjEzMTM4NDg1` - This is the payment token used for the payment.
        + paymentMethod:`CC` - This is the payment method used for the payment.
        + paymentDate:`2017-10-01` - This is the payment date.
        + status:`FAILED` - This is the status of the payment.
    + retryPayment (object, optional) - These are [details about the payment retry](#retrypaymentobject) in the case where a payment has failed.
        + amount:`4999` - This is the amount of the payment, in minor units.
        + accountId:`1000055555` - This is the merchant account that is used to process the payment.
        + paymentToken:`CNjEzMTM4NDg1` - This is the payment token used for the payment.
        + paymentMethod:`CC` - This is the payment method used for the payment.
        + paymentDate:`2017-10-06` - This is the payment retry date.
    + nextPayment (object, optional) - These are [details about the next payment](#nextpaymentobject).
        + amount:`4999` - This is the amount of the payment, in minor units.
        + accountId:`1000055555` - This is the merchant account that is used to process the payment.
        + paymentToken:`CNjEzMTM4NDg1` - This is the payment token used for the payment.
        + paymentMethod:`CC` - This is the payment method used for the payment.
        + paymentDate:`2017-11-01` - This is the next payment date.
+ links (array, required) - This is an array of [links](#linksobject).
    + (object)
        + rel:`self` (string, required) - This is the link type that allows different endpoints to be targeted depending on the end state of the transaction.
        + href:`https://api.test.paysafe.com/subscriptionsplans/v1/subscriptions/382d5b82-5e3f-40b7-a36d-eb982116c2b3` (string, required) - This is the URI of the resource.
+ _expandable (object, required) - This displays expandable resources.
    + plan:`https://api.test.paysafe.com/subscriptionsplans/v1/plans/e067d83f-add7-4b6b-8884-dfa8693dde1f`
    + profile: `https://api.test.paysafe.com/customervault/v1/profiles/a5f1889d-f1be-4bbf-941d-fd9b8d09d5b1`

## Subscription Response Expansion
+ id:`382d5b82-5e3f-40b7-a36d-eb982116c2b3` (string, required) - This is the unique subscription ID.
+ Include Subscription
+ creationTime:`2017-02-14T15:12:18Z` (string, required) - This is the date and time the subscription was created.
+ billingPeriodStartDate:`2017-01-01` (string, optional) - This is the date the billing period starts.
+ billingPeriodEndDate:`2017-12-31` (string, optional) - This is the date the billing period ends.
+ schedule (object, optional)  
    + previousPayment (object, optional) - These are [details about the previous payment](#previouspaymentobject).
        + amount:`4999` - This is the amount of the payment, in minor units.
        + accountId:`1000055555` - This is the merchant account that is used to process the payment.
        + paymentToken:`CNjEzMTM4NDg1` - This is the payment token used for the payment.
        + paymentMethod:`CC` - This is the payment method used for the payment.
        + paymentDate:`2017-10-01` - This is the payment date.
        + status:`FAILED` - This is the status of the payment.
    + retryPayment (object, optional) - These are [details about the payment retry](#retrypaymentobject) in the case where a payment has failed.
        + amount:`4999` - This is the amount of the payment, in minor units.
        + accountId:`1000055555` - This is the merchant account that is used to process the payment.
        + paymentToken:`CNjEzMTM4NDg1` - This is the payment token used for the payment.
        + paymentMethod:`CC` - This is the payment method used for the payment.
        + paymentDate:`2017-10-06` - This is the payment retry date.
    + nextPayment (object, optional) - These are [details about the next payment](#nextpaymentobject).
        + amount:`4999` - This is the amount of the payment, in minor units.
        + accountId:`1000055555` - This is the merchant account that is used to process the payment.
        + paymentToken:`CNjEzMTM4NDg1` - This is the payment token used for the payment.
        + paymentMethod:`CC` - This is the payment method used for the payment.
        + paymentDate:`2017-11-01` - This is the next payment date.
+ plan (object, required) - These are details about the plan.
    + Include Plan Response Expansion
+ profile (object, required) - These are details about the customer profile.
    + Include Profile
+ links (array, required) - This is an array of [links](#linksobject).
    + (object)
        + rel:`self` (string, required) - This is the link type that allows different endpoints to be targeted depending on the end state of the transaction.
        + href:`https://api.test.paysafe.com/subscriptionsplans/v1/subscriptions/382d5b82-5e3f-40b7-a36d-eb982116c2b3` (string, required) - This is the URI of the resource.
+ _expandable (object, required) - This displays expandable resources.
    + plan:`https://api.test.paysafe.com/subscriptionsplans/v1/plans/e067d83f-add7-4b6b-8884-dfa8693dde1f`
    + profile: `https://api.test.paysafe.com/customervault/v1/profiles/a5f1889d-f1be-4bbf-941d-fd9b8d09d5b1`




## Empty Set
{
}